# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbconnect1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 121, 16))
        self.label.setObjectName("label")
        self.labelresult = QtWidgets.QLabel(Form)
        self.labelresult.setGeometry(QtCore.QRect(40, 250, 341, 16))
        self.labelresult.setObjectName("labelresult")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(170, 30, 201, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtoncreateDB = QtWidgets.QPushButton(Form)
        self.pushButtoncreateDB.setGeometry(QtCore.QRect(40, 180, 151, 28))
        self.pushButtoncreateDB.setObjectName("pushButtoncreateDB")
        
        self.pushButtonDBcon = QtWidgets.QPushButton(Form)
        self.pushButtonDBcon.setGeometry(QtCore.QRect(210, 180, 161, 28))
        self.pushButtonDBcon.setObjectName("pushButtonDBcon")
        
        self.pushButtoncreateDB.clicked.connect(self.create_database) 
        self.pushButtonDBcon.setObjectName("pushButtonDbcon") 
        self.pushButtonDBcon.clicked.connect(self.db_connect)  
        self.labelresult = QtWidgets.QLabel(Form)
        self.labelresult.setGeometry(QtCore.QRect(10, 270, 391, 20))
        
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelresult.setFont(font)
        self.labelresult.setObjectName("labelResult")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def create_database(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password=""
                )
            cursor = mydb.cursor()
            dbname = self.lineEdit.text()
            cursor.execute("CREATE DATABASE {}".format(dbname))
            self.labelresult.setText("Database {} created ".format(dbname))
        except mc.Error as e:
            self.labelresult.setText("Database creation failed")
            
    def db_connect(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
                )
            self.labelresult.setText("There is Connection")
        except mc.Error as err:
            self.labelresult.setText("Error In Connection")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CREATE DATABASE"))
        self.labelresult.setText(_translate("Form", "TextLabel"))
        self.pushButtoncreateDB.setText(_translate("Form", "DATABASE CREATION"))
        self.pushButtonDBcon.setText(_translate("Form", "DATABASE CONNECTION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
